import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

#import dataset from local
data=pd.read_csv("arcades revenues with dr awared.csv")
#retrive data
x=data["Year"]
y1=data["Total Revenue generated by arcades"]
y2=data["Computer Science doctorates awarded in the US"]
#plot graph
fig, ax1 = plt.subplots(1,1,figsize=(15,5))
ax2= ax1.twinx()
ax1.set_ylim([1,2])
ax2.set_ylim([500,2000])
line1=ax1.plot(x,y1,color='red')
line2=ax2.plot(x,y2,color='black')
ax1.set_title("Total Revenue generated by arcades correlates with Computer Science doctorates awarded in the US")
ax1.set_ylabel("Arcade revenue")
ax2.set_ylabel("Computer science doctorates",rotation=270,labelpad=15)
fig.legend(loc=(0.4,0))
ax2.scatter(x,y2,color='black')
ax1.scatter(x,y1,color='red')
ax1.grid()
plt.savefig('task21.png')
